return {
  max_filesize = 1024 * 1024, -- 1 MiB
  ---@type "tokyonight"|"catppuccin"|"rose-pine"|"material"|"kanagawa"
  colorscheme = "catppuccin",
  ---@type "tokyonight"|"catppuccin"|"rose-pine"|"material-stealth"|"kanagawa"
  statusline_colorscheme = "catppuccin",
  ---@type boolean
  transparent_background = true,
  oil = {
    hidden_file_patterns = {
      "^%.git$",
      "^node_modules$",
      "^%.cache$",
      "%.DS_Store",
    },
    always_hidden_patterns = {
      "^%.%.$",
    },
  },
  ignore_buftypes = {
    "TelescopePrompt",
    "checkhealth",
    "gitcommit",
    "gitrebase",
    "help",
    "hgcommit",
    "lspinfo",
    "man",
    "nofile",
    "notify",
    "oil",
    "prompt",
    "qf",
    "query",
    "svn",
    "terminal",
  },
  treesitter_parsers = {
    "bash",
    "c",
    "comment",
    "cpp",
    "dockerfile",
    "git_config",
    "git_rebase",
    "gitcommit",
    "gitignore",
    "go",
    "gosum",
    "gomod",
    "gowork",
    "ini",
    "vimdoc",
    "json",
    "json5",
    "jsonc",
    "javascript",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "python",
    "regex",
    "rust",
    "scala",
    "sql",
    "typescript",
    "toml",
    "vim",
    "yaml",
    "hyprlang",
  },
  formatters = {
    "stylua",
    "isort",
    "black",
    "sql-formatter",
    "mdformat",
    "yamlfix",
    "shfmt",
    "prettier",
    "prettierd",
    "goimports",
    "gofumpt",
  },
  linters = {
    "selene",
    "vulture",
    "markdownlint",
    "shellcheck",
    "hadolint",
    "jsonlint",
    "golangci-lint",
    "yamllint",
    "sqlfluff",
  },
  mason_auto_installed = {},
}
