return {
  "catppuccin/nvim",
  name = "catppuccin",
  lazy = require("core.vars").colorscheme ~= "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      flavour = "mocha",
      background = { light = "latte", dark = "mocha" },
      transparent_background = require("core.vars").transparent_background,
      term_colors = true,
      integrations = {
        mason = true,
        semantic_tokens = true,
        treesitter = true,
        treesitter_context = true,
        nvimtree = true,
        telescope = {
          enabled = true,
          style = "nvchad",
        },
        cmp = true,
        gitsigns = true,
        noice = true,
        notify = true,
        mini = {
          enabled = true,
          indentscope_color = "lavender",
        },
        neotest = true,
        neogit = true,
        dap = {
          enabled = true,
          enabled_ui = true,
        },
        which_key = true,
        illuminate = {
          enabled = true,
          lsp = false,
        },
      },
      color_overrides = {
        mocha = {
          rosewater = "#ea6962",
          flamingo = "#ea6962",
          red = "#ea6962",
          maroon = "#ea6962",
          pink = "#d3869b",
          mauve = "#d3869b",
          peach = "#e78a4e",
          yellow = "#d8a657",
          green = "#a9b665",
          teal = "#89b482",
          sky = "#89b482",
          sapphire = "#89b482",
          blue = "#7daea3",
          lavender = "#7daea3",
          text = "#ebdbb2",
          subtext1 = "#d5c4a1",
          subtext0 = "#bdae93",
          overlay2 = "#a89984",
          overlay1 = "#928374",
          overlay0 = "#595959",
          surface2 = "#4d4d4d",
          surface1 = "#404040",
          surface0 = "#292929",
          base = "#1d2021",
          mantle = "#191b1c",
          crust = "#141617",
        },
      },
    })
    vim.cmd([[colorscheme catppuccin]])
  end,
}
