#!/usr/bin/env zsh

# Profile zsh
[[ ${ZPROFRC:-0} -ne 1 ]] || zmodload zsh/zprof
alias zprofrc="ZPROFRC=1 zsh"

# These operations write to stdout so we should run those before starting instant prompt
command -v fnm &> /dev/null && eval "$(fnm env --use-on-cd)"

# Enable p10k instant prompt (if available)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" && ${ZPROFRC:-0} -eq 0 ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Sane defaults for ZSH. Even if things get borked, let's have the base set
[[ ! -f $ZDOTDIR/lib/essentials.zsh ]] || source $ZDOTDIR/lib/essentials.zsh

# Add custom completions to fpath
fpath=(${ZDOTDIR:-$HOME/.config/zsh}/completions $fpath)

# Set any and all zstyles
[[ ! -f ${ZDOTDIR:-$HOME}/.zstyles ]] || source ${ZDOTDIR:-$HOME}/.zstyles

# Load antidote
source ${ZDOTDIR:-$XDG_CONFIG_HOME}/lib/antidote.zsh

# Homebrew setup
command -v brew &> /dev/null && eval "$(brew shellenv)"

# Source p10k
[[ ! -f $XDG_CONFIG_HOME/zsh/.p10k.zsh ]] || source $XDG_CONFIG_HOME/zsh/.p10k.zsh

# Any machine-specific configuration goes into .zshrc_local
[[ ! -f $ZDOTDIR/.zshrc_local ]] || source $ZDOTDIR/.zshrc_local

# Finish profiling by calling zprof
[[ "$ZPROFRC" -eq 1 ]] && zprof
[[ -v ZPROFRC ]] && unset ZPROFRC
