k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: true
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: eks-us-west-2-prod
  currentCluster: arn:aws:eks:us-west-2:442501350342:cluster/eks-us-west-2-prod
  clusters:
    arn:aws:eks:ap-south-1:442501350342:cluster/eks-ap-south-1-non-prod:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-west-2:442501350342:cluster/eks-us-west-2-non-prod:
      namespace:
        active: fss-pricing-service
        lockFavorites: false
        favorites:
        - fss-pricing-service
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    arn:aws:eks:us-west-2:442501350342:cluster/eks-us-west-2-prod:
      namespace:
        active: prod-pricing-service
        lockFavorites: false
        favorites:
        - prod-pricing-service
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/kj/tnqp58s95991gc67wbppx73h0000gq/T/k9s-screens-amitsingh
