local C = {
  -- Copied from: https://github.com/mikesmithgh/borderline.nvim/blob/1bc8237a41f5277b35aaf153635f927aa8fa5224/lua/borderline/borders.lua
  ---@enum border_styles
  border_styles = {
    none = { "", "", "", "", "", "", "", "" },
    double = { "╔", "═", "╗", "║", "╝", "═", "╚", "║" },
    single = { "┌", "─", "┐", "│", "┘", "─", "└", "│" },
    shadow = {
      "",
      "",
      { " ", "FloatShadowThrough" },
      { " ", "FloatShadow" },
      { " ", "FloatShadow" },
      { " ", "FloatShadow" },
      { " ", "FloatShadowThrough" },
      "",
    },
    rounded = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    solid = { " ", " ", " ", " ", " ", " ", " ", " " },
    block = { "▛", "▀", "▜", "▐", "▟", "▄", "▙", "▌" },
    inner_block = { " ", "▄", " ", "▌", " ", "▀", " ", "▐" },
    thinblock = { "🭽", "▔", "🭾", "▕", "🭿", "▁", "🭼", "▏" },
    inner_thinblock = { " ", "▁", " ", "▏", " ", "▔", " ", "▕" },
    bullet = { "•", "•", "•", "•", "•", "•", "•", "•" },
    star = { "*", "*", "*", "*", "*", "*", "*", "*" },
    simple = { "+", "-", "+", "|", "+", "-", "+", "|" },
    heavy_single = { "┏", "━", "┓", "┃", "┛", "━", "┗", "┃" },
    light_shade = { "░", "░", "░", "░", "░", "░", "░", "░" },
    medium_shade = { "▒", "▒", "▒", "▒", "▒", "▒", "▒", "▒" },
    dark_shade = { "▓", "▓", "▓", "▓", "▓", "▓", "▓", "▓" },
    arrow = { "↗", "→", "↘", "↓", "↙", "←", "↖", "↑" },
    full_block = { "█", "█", "█", "█", "█", "█", "█", "█" },
    diff = {
      { "┌", "DiffText" },
      { "─", "DiffText" },
      { "┐", "DiffText" },
      { "│", "DiffText" },
      { "┘", "DiffText" },
      { "─", "DiffText" },
      { "└", "DiffText" },
      { "│", "DiffText" },
    },
  },
  misc_icons = {
    NeovimIcon = "",
  },
  kind_icons = {
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Property = "󰜢",
    Unit = "",
    Value = "󰎠",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "",
    Array = "󰅪",
    Boolean = "",
    Component = "󰅴",
    Fragment = "󰅴 ",
    Key = "󰌋 ",
    Macro = "󰁥 ",
    Module = " ",
    Namespace = "󰰔 ",
    Null = "␀ ",
    Number = "#",
    Object = "󰲟 ",
    Package = " ",
    Parameter = " ",
    StaticMethod = "󰰑 ",
    String = "󰅳 ",
    TypeAlias = " ",
  },
  -- Provide pretty names to LSPs in the status line
  lsps = {
    bashls = { name = "Bash LS", priority = 20 },
    clangd = { name = "Clang LS", priority = 20 },
    dockerls = { name = "Docker LS", priority = 20 },
    eslint = { name = "ESLint", priority = 15 },
    gopls = { name = "Go LS", priority = 20 },
    jsonls = { name = "JSON LS", priority = 20 },
    lua_ls = { name = "Lua LS", priority = 20 },
    marksman = { name = "Marksman", priority = 20 },
    basedpyright = { name = "Python LS", priority = 20 },
    ruff = { name = "Ruff LS", priority = 15 },
    terraformls = { name = "Terraform LS", priority = 20 },
    ts_ls = { name = "Typescript LS", priority = 20 },
    yamlls = { name = "YAML LS", priority = 20 },
    cssls = { name = "CSS LS", priority = 20 },
    rust_analyzer = { name = "Rust LS", priority = 20 },
  },
  diagnostics_icons = {
    [vim.diagnostic.severity.ERROR] = "󰅚 ",
    [vim.diagnostic.severity.WARN] = "󰗖 ",
    [vim.diagnostic.severity.INFO] = " ",
    [vim.diagnostic.severity.HINT] = " ",
  },
}

return C
