return {
  big_file = {
    size_in_bytes = 1 * 1024 * 1024, -- 1 MiB
    line_count = 5000,
  },
  colorscheme = {
    name = "kanso",
    transparent_background = false,
  },
  last_location_excluded_filetypes = {
    "NvimTree",
    "Trouble",
    "TelescopePrompt",
    "help",
    "gitcommit",
  },
  meta_filetypes = {
    "",
    "PlenaryTestPopup",
    "TelescopePrompt",
    "checkhealth",
    "dap-view",
    "dap-float",
    "dap-view-help",
    "dap-view-term",
    "dap-repl",
    "dbout",
    "diff",
    "git",
    "gitcommit",
    "gitrebase",
    "gitsigns-blame",
    "kitty-scrollback",
    "nvim-undotree",
    "leetcode.nvim",
    "man",
    "taskedit",
    "codecompanion",
    "help",
    "hgcommit",
    "log",
    "lspinfo",
    "man",
    "msg",
    "mininotify-history",
    "neotest-output",
    "neotest-output-panel",
    "neotest-summary",
    "nofile",
    "notify",
    "oil",
    "prompt",
    "qf",
    "lazy",
    "OverseerList",
    "query",
    "sagafinder",
    "sagarename",
    "scratch",
    "startuptime",
    "svn",
    "terminal",
    "tsplayground",
  },
}
